services:
  postgres:
    image: postgres:17.4
    container_name: emt_lab_db
    restart: always
    environment:
      POSTGRES_DB: emt_lab
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./02-views.sql:/docker-entrypoint-initdb.d/02-views.sql
      - ./03-data.sql:/docker-entrypoint-initdb.d/03-data.sql
    ports:
      - "2345:5432"
volumes:
  pgdata: